src/aurelia.js
src/index.js
src/plugins.js

Bolster public-facing docunmentation.
Fixes #2 JSDoc documentation for public methods.

doc(framework): add yuidoc documentation.

---

build/args.js
build/tasks/prepare-release.js
package.json

This feature will ease preparation for releases. Syntax is:
```Shell
gulp bump-version --bumptype=patch
```
If no argument value is supplied, patch will be use.
Valid values are: `major|minor|patch|prerelease`.
Supplying an invalid value will cause an error.

feat(build): add command line argument for semver bump. resolve #28

---

src/aurelia.js

Prevent forms without an `action` to submit. This is good practice adopted from angular.

feat(framework): prevent forms without [action] from submiting

---

.gitignore
build/tasks/test.js
package.json

Signed CLA as Andreas Krummsdorf
You also might be interested in https://github.com/litixsoft/karma-detect-browsers, which allows you to run the karma tests in all browser of the current system. But thats another topic :-)
Additionally, i wonder you are using some kind of CI System? I found https://travis-ci.org very useful for open source projects. It's really easy to integrate and it will run the tests on every commit/pull-request.

chore: add task 'cover' to run tests with code coverage

---

doc/article/en-US/a-production-setup.html
doc/article/en-US/business-advantages.html
doc/article/en-US/technical-benefits.html

Git seems to think I made extensive changes to the first paragraph in `business-advantages.html`. All I did was fix the spelling of "competitive." Elsewhere, I fixed a few typos, added an Oxford comma, and removed an unnecessary comma.
I changed the sentence in `a-production-setup.html` to not use the passive voice.
I added a comma in `technical-benefits.html`.

(doc): minor grammar and spelling fixes

---

doc/article/en-US/bundling-your-app-for-deploy.md

The bundles.json example in Full HTML Import Bundle Config has an extra comma that breaks `gulp bundle`.

Invalid JSON in Full Config example.

---

doc/article/en-US/cheat-sheet.md

This tripped me up a couple of times when binding variables to custom elements, not sure if this is the best place exactly to put it, but I think it needs to be included somewhere.

(doc): add a clear example of dash-case to camelCase binding

---

src/aurelia.js
test/aurelia.spec.js

When enhancing a page, if no applicationHost is specified (either string
for the id of the element, or an element itself) enhance will use the
body as the host.

feat(enhance): use document.body as fallback

---

doc/article/en-US/getting-started.md

As indicated here: https://github.com/aurelia/beginner-kits/issues/17

Added note explaining not to run `jspm install` on the getting-started kits.

---

doc/article/en-US/cheat-sheet.md

Expanded the "Custom Element Without View-Model Declaration" samples to demonstrate:
* that you can declare multiple bindable properties by separating with commas
* that you can bind to static values

doc(cheet-sheet.md): clarify Custom Element Without View-Model

---

doc/article/en-US/the-aurelia-cli.md

Resolves: https://github.com/aurelia/cli/issues/333
Update the docs to describe how to use various flags to compile build
revisions in different environments.

docs(aurelia-cli): describe build flags for revision numbers

---

doc/article/en-US/the-aurelia-cli.md

Need to warn users to disable TS building within VS or the CLI breaks.

Update the-aurelia-cli.md to warn users to disable TS compile in VS build process

---

doc/article/en-US/the-aurelia-cli.md

Sorry I missed the `doc()` prefix on commit message...

Brief usage notes for scoped packages

---

doc/article/en-US/securing-your-app.md

doc: Add more type information to Typescript AuthorizeStep
Having the run function's second parameter, in the AuthorizeStep class, as Function was giving me errors in Typescript as a 'Function' type has no 'cancel' property. In addition to updating that, I added some additional type information to the rest of the class.

Add more type information to Typescript AuthorizeStep

---

doc/article/en-US/contact-manager-tutorial.md

Changed "UpperCammelCase" to "UpperCamelCase" within the "Building Out the Contact List" section of the tutorial.

Minor Typo Fix in Contact Manager Tutorial

---

doc/article/en-US/app-configuration-and-startup.md

While refactoring existing angular application into Aurelia gradually (module by module) it became necessary to add multiple enhance statements using templating engine, which is not described in documentation
No breaking changes
Related to [Issue 593](https://github.com/aurelia/framework/issues/593)

Add info about multiple enhance statements to the doc

---

doc/article/en-US/contact-manager-tutorial.md

When running `au new` I got an error during 'installing project dependencies' during git clone requirejs.
I tried updating npm, updating node, clearing cache, reinstalling aurelia CLI, but still got the same error. When I tried updating git, I got the option to make git available on bash only or make it available on command prompt too. I suspected this was the cause and made git available on command prompt. After that I didn't get the same error when running au new.

error when running au new caused by git installation option

---

src/framework-configuration.js

Left a comment explaining why we don't want to use PLATFORM.moduleName here, although there are plenty of module names in the file.
See aurelia/pal#21

style(comments): added comments about moduleName

---

src/aurelia.js

`start()` had some kind of race condition, as it would return a resolved Promise before the startup process actually completed. An illustration of the problem:
```js
let p1 = aurelia.start();  
// p1 is pending
let p2 = aurelia.start(); 
// p2 is resolved
```
In addition to being settled too early, that second Promise could resolve although the startup process ultimately rejects.
The code above looks dumb, but a realist application could be a plugin that wants to execute something after its application has started. An easy way to do that is:
```js
// In plugin/index.js
export function configure(aurelia) {
aurelia.start().then(() => /* do stuff when started */);
}
```
CC @niieani

fix(startup): start() incorrectly returns a resolved promise

---

src/framework-configuration.js

I modified `feature()` so that it accepts explicits `/index` inputs. 
This change makes the API play nice with our new `moduleName`, like so:
```js
aurelia.use.feature(PLATFORM.moduleName('data-grid/index'))
```
I discovered that the original code had support for extensions, like you could pass `data-grid/index.js`. 
I left that behavior unchanged, although it seems to me that `resourcesRelativeTo` is inconsistent when using that code path 😶

feat(config): .feature() accepts explicit /index.

---

doc/article/en-US/the-aurelia-cli.md

Add description of the 'append' feature added to [aurelia/cli](https://github.com/aurelia/cli) in [#471](https://github.com/aurelia/cli/pull/471), with the specific use case for which it was added.

docs(the-aurelia-cli): add description of append feature

---

doc/article/en-US/the-aurelia-cli.md

I followed the tutorial and this stumped me because of invalid JSON.

Correct typo in copyFiles JSON

---

doc/article/en-US/app-configuration-and-startup.md

The link to polyfill MutationObserver for IE10-9 is outdated. In this change, a clear and alternative library to polyfill MutationObserver is provided.

app-configuration-and-startup.md

---

doc/article/en-US/the-aurelia-cli.md

documentation of https://github.com/aurelia/cli/pull/576

doc(cli): describe configuration of packages outside node_modules

---

doc/article/en-US/app-configuration-and-startup.md

Removed old reference of MutationObserver from previous doc (existed in JSPM example) and replaced it with the new shim:
Old doc instructed to install `webcomponents/webcomponentsjs/MutationObserver`.
But new doc uses `mutationobserver-shim/MutationObserver`. However, a trace of old shim existed in JSPM code.
Also, provided an example how to use the polyfill file in the webpack.config.js.

Update MutationObserver for JSPM example

---

doc/article/en-US/the-aurelia-cli.md

I'm submitting a bug fix
Current behavior:
http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/bundling-jspm/9
{
"name":"jquery",
"path":"../node_modules/jquery/dist",
"main":"jquery.min",
"export": "$"
}
is incorrect
Expected/desired behavior:
{
"name":"jquery",
"path":"../node_modules/jquery/dist",
"main":"jquery.min",
"exports": "$"
}
as per http://requirejs.org/docs/api.html
What is the motivation / use case for changing the behavior?
avoid confusion for folks using old libraries

fix(786) documentation says export instead of exports

---

doc/article/en-US/app-configuration-and-startup.md

Related to aurelia/dialog#233 and [SO](https://stackoverflow.com/questions/46224130/google-tag-manager-preview-mode-does-not-work-in-aurelia).

doc(app-configuration-and-startup): add warning about setRoot

---

doc/article/en-US/contact-manager-tutorial.md

Updated info regarding TypeScript Definition Files installation for TypeScript version starting from 2.0, as per [typings documentation](https://github.com/typings/typings)

Updated nprogress install info(TS >= 2.0)

---

doc/article/en-US/app-configuration-and-startup.md

Users need to manually initialize the PAL before importing Aurelia
modules in their configuration module.

doc(app-config): add a warning about aurelia/pal-browser#17

---

src/framework-configuration.js

So we can do `aurelia.use.developmentLogging(environment.debug ? 'debug' : 'warn');` to still see error/warn in production app.

feat(log): support optional log level param to developmentLogging().

---

src/aurelia.js
test/aurelia.spec.js

Ability to use view model class as first argument for `setRoot`, enable static scenario for `setRoot`
Demo:
https://stackblitz.com/edit/static-aurelia-root?file=index.js (line 26)
@EisenbergEffect

feat(Aurelia): ability to define root with constructor

---

CONTRIBUTING.md
README.md

change to readme document to include simple getting started example, links to documentation, and re-organisation of contributing details
first step towards addressing issue #318

(doc): change to readme to include getting started details

---

src/framework-configuration.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()
