build/tasks/test.js
feat(tests): Added Karma gulp tasks
`test` and `tdd` tasks for running Karma.
=> Added Karma gulp tasks

src/plugins.js
Fixes same problem as https://github.com/aurelia/templating/pull/122.
=> Adds support for .ts files.

src/framework-configuration.js
This is a small fix of generated d.ts files.
=> d.ts fix - parameter config in feature and plugin method is optional

doc/article/en-US/cheat-sheet.md
=> doc(typos): fix cheat sheet typos

doc/article/en-US/cheat-sheet.md
Fix a long time typo...
Edit: fix a typo in a typo PR, amazing... hahaha
=> Fix typo in docs

src/framework-configuration.js, test/framework-configuration.js
Still work in progress. Got `skeleton-navigation` working.
=> JSPM v0.17.0/SystemJS Compatibility

doc/article/en-US/angular1-to-aurelia.md
Add documentation for migrating an Angular 1.x app to Aurelia.
=> doc(angular): add Angular to Aurelia migration

src/framework-configuration.js
All tests are passing now. lint is OK too.
=> Fix getExt

doc/article/en-US/app-configuration-and-startup.md
See aurelia/skeleton-navigation#396
=> doc(webpack): add Jade custom view location example

doc/article/en-US/cheat-sheet.md
Shows usage and how to configure
=> chore(cheatsheet): add observable decorator

src/aurelia.js
=> doc(aurelia): adding host property definition

doc/article/en-US/end-to-end-testing.md
Minor typo: wiating --> waiting
=> docs(e2e): fix typo in e2e docs

doc/article/en-US/integrating-with-polymer.md
Adjusted the comment format to comply with [comment format guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit).
=> Add additional bower instructions

doc/article/en-US/bundling-your-app-for-deploy.md
Cleanup code examples which contain
comma related syntax errors.
=> doc(bundling): fix comma syntax errors

doc/article/en-US/app-configuration-and-startup.md
=> doc: update app-configuration-and-startup.md

doc/article/en-US/cheat-sheet.md
Change AuthorizeStep's next parameter type to Next.
=> doc(cheat-sheet): change AuthorizeStep's next parameter type

src/aurelia.js
=> fix(aurelia): resolve promise in Aurelia.enhance

doc/article/pt-BR/what-is-aurelia.md
Translation of "What is Aurelia" article to Brazilian Portuguese.
=> doc(what): translate "What is Aurelia?" article to Portuguese

doc/article/en-US/contact-manager-tutorial.md
Change 'a new items' to 'some new items'.
=> Correct grammar in budles section of tutorial

doc/article/en-US/the-aurelia-cli.md
Covers features added:
https://github.com/aurelia/cli/pull/326
https://github.com/aurelia/cli/pull/305
=> doc(aurelia-cli): add docs for revisions and bundling

doc/article/en-US/contact-manager-tutorial.md
adds information about UpperCamelCase and dashed-case conventions for defining custom elements
=> docs(casing): info about upper/dashed case

doc/article/en-US/app-configuration-and-startup.md
Import requestAnimationFrame polyfill directly. https://github.com/chrisdickinson/raf/pull/31
=> doc(config-and-startup): update polyfill import

doc/article/en-US/integrating-with-polymer.md
Changed $ jspm install 'aurelia-polymer@^1.0.0-beta' into $ jspm install aurelia-polymer@^1.0.0-beta
=> Removed unwanted single quotes in jspm command

doc/article/en-US/creating-components.md
Partly fixes aurelia/documentation#273
=> Fix typos with periods

doc/article/en-US/creating-components.md
=> doc(creating-components): add note about implmenting bind callback

doc/article/en-US/cheat-sheet.md
Change to add all resolvers to "Available Resolvers"
=> doc: update cheat sheet for DI resolvers

doc/article/en-US/cheat-sheet.md
Possible useful info to have. Thanks to TylerJPresley for assisting on Gitter.
=> doc(cheat-sheet) update root vs route screen activation lifecycle

doc/article/en-US/the-aurelia-cli.md
From the answer for: http://stackoverflow.com/questions/38934736/deploying-an-aurelia-cli-built-app
=> doc(the-aurelia-cli): Add deployment instructions

doc/article/en-US/contact-manager-tutorial.md
(First, thanks for an absolutely great framework @EisenbergEffect (and all the rest of you). Very much appreciated - I was actually thinking if I might have to roll my own just to get _something_ that plays decently well with TypeScript, but after trying it out now for half an hour, I must say that the initial impression is _great_. It feels much more modern than some of the competing, older frameworks.)
Went through the "todo" guide first, and now wandering through the "contact manager" one, I noted some irregularities in the formatting, so here goes - my very first (but hopefully not last 😄) contribution to the project. (I assume that it's this example that is mis-formatted, since the others use the "whitespace-before-curly" syntax.)
=> Whitespace fixes

doc/article/en-US/the-aurelia-cli.md
Documentation about how to copy files in the CLI. Related to https://github.com/aurelia/cli/pull/476.
=> doc(the-aurelia-cli): add instructions about the copyFiles feat

doc/article/en-US/cheat-sheet.md
spotted incorrect spellings
.......I don't think it's "that" kind of establishment :wink:
=> changed "some-massage" to "some-message"

ISSUE_TEMPLATE.md
Add a line telling people that their issues will be closed if they ignore the issue template.
=> chore(issue): update issue template

doc/article/en-US/the-aurelia-cli.md
I, I think like many others, struggled to get jquery and bootstrap fully imported into my aurelia app (started with contact-manager sample).  https://github.com/aurelia/bundler/issues/92 seemed to be the best answer, so I took a stab at tweaking the docs to reflect the solution that worked for me as proposed by @ERobishaw.
=> Refs aurelia/bundler#92 - Attempting to fix jquery/bootstrap docs.

doc/article/en-US/the-aurelia-cli.md
closes https://github.com/aurelia/cli/issues/315
=> doc(cli): added information on the baseUrl

ISSUE_TEMPLATE.md
Trying to make it more clear that questions/support request need to go to Stack overflow. 
Add Aurelia CLI to module loader list.
Update version numbers to latest. 
Remove duplicate "What is the expected behavior?" question.
=> doc(issue_template): update issue template

doc/article/en-US/contact-manager-tutorial.md
should prevent the error mentioned in https://github.com/aurelia/cli/issues/508
=> doc(tutorial): restart after adding bootstrap

doc/article/en-US/the-aurelia-cli.md
documentation for https://github.com/aurelia/cli/pull/642
=> doc(the-aurelia-cli): explain minification options

doc/article/en-US/contact-manager-tutorial.md
Add a note explaining that you should restart au run after npm installing new dependencies.
Fixes issue https://github.com/aurelia/documentation/issues/326
=> docs(contact-manager): note for restarting au run

README.md
Update to new doc links in hub.
=> chore(docs): fix hub links, add discourse

doc/article/en-US/app-configuration-and-startup.md
Regarding #570, this adds an example of adding and configuring a plugin.
=> add instructions on adding and configuring a plugin.

config.js, src/framework-configuration.js, test/framework-configuration.js
@EisenbergEffect This is the follow up PR for aurelia/templating#616 aurelia/templating#617
@jdanyow @jods4
=> feat(config): accepts classes beside module id string

README.md
* Add some of the unique characteristics of Aurelia
* Add a playfull tone
* More extensive example that shows off some binding syntax
* Add link to CLI basics doc for quickly getting started
See https://github.com/aurelia/aurelia/issues/318
=> doc(readme): extend example, add some info
